### ISSUE TITLE
Error parsing json to LUA table

### ISSUE THREAD

**Issue by Cad01** [neutrino85/MyRenaultZoeDomoticz#1]
Hi I try to use your script with our car (twingo ZE) but I always get this error:

`2022-01-17 15:00:09.309 Error: dzVents: Error: (3.1.8) Zoé_async 2.0: Error parsing json to LUA table: /home/pi/domoticz/dzVents/runtime/JSON.lua:1234: /home/pi/domoticz/dzVents/runtime/JSON.lua:808: expected comma or '}' at byte 434 of: { "battery" : {"data": {"type": "Car", "id": "VF1AH000*********", "attributes": {"timestamp": "2022-01-17T05:57:35Z", "batteryLevel": 53, "batteryTemperature": 20, "batteryAutonomy": 78, "batteryCapacity": 0, "batteryAvailableEnergy": 11, "plugStatus": 0, "chargingStatus": -1.1, "chargingRemainingTime": 70, "chargingInstantaneousPower": 7.2}}},"cockpit" : {"type": "FUNCTIONAL", "messages": [{"code": "err.func.403", "message": "{"errors":[{"status":"403","code":"security.access","detail":"Access is denied for this resource"}]}"}], "errors": [{"errorCode": "err.func.403", "errorMessage": "{"errors":[{"status":"403","code":"security.access","detail":"Access is denied for this resource"}]}"}], "error_reference": "FUNCTIONAL"},"chargemode" : {"data": {"type": "Car", "id": "VF1AH000*********", "attributes": {"dateTime": "2022-01-17T14:00:04.79637Z", "mode": "always", "schedules": [{"id": 1, "activated": false, "monday": {"startTime": "T05:00Z", "duration": 120}}, {"id": 2, "activated": false}, {"id": 3, "activated": false}, {"id": 4, "activated": false}, {"id": 5, "activated": false}]}}},"location" : {"data": {"type": "Car", "id": "VF1AH000*********", "attributes": {"gpsDirection": "None", "lastUpdateTime": "2022-01-17T05:56:19Z", "gpsLongitude": *.65522039, "gpsLatitude": **.04313648}}},"test" : " ``"}`

#I edited the VIN and postion for privacy reasons.

Maybe can you help me to fix the problem?

**Comment by usky73** [comment]
What I recommend is to test it in a terminal using sudo command first.
If you can see the json answer it is working, if not the issue can be on installation or library of python. It was my case. I had to install the library using sudo command not as a user

**Comment by neutrino85** [comment]
The JSon generate by Renault doesn't respect the JSON specification...
And it looks like your Twingo doesn't support the cockpit api.
You can test this
`	url = kamereonrooturl + '/commerce/v1/accounts/' + kamereonaccountid + '/kamereon/kca/car-adapter/v1/cars/' + vin + '/cockpit?country=FR'
`
in MyRenault.py line 155
(change v2 by v1)

**Comment by Cad01** [comment]
Changing to v1 doesn't change the outcome.
I did a quick and dirty workaround now. I replaced the `+ kamereon_cockpit` in line 441 and 454 and  with an fixed value with the expected coding. Which gives me all of the other functions. It seems indeed that the twingo doesn't support the cockpit api. I have to dig into the app of our leasing company which does state the milage.
